# Generated by Django 4.2.30 on 2026-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email бизнеса'),
        ),
        migrations.AddField(
            model_name='business',
            name='employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AddField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='business',
            name='warehouse_area',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Площадь склада'),
        ),
    ]
