# Generated by Django 4.2.30 on 2026-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_address_business_city_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Заметка'),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
