# Generated by Django 4.2.30 on 2026-07-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Данные регистрации'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен'),
        ),
    ]
