# Generated by Django 4.2.30 on 2026-07-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_emailverification_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('supply', 'Поставка'), ('product', 'Товар'), ('price', 'Цена'), ('auth', 'Вход'), ('user', 'Сотрудник'), ('settings', 'Настройки')], max_length=15, verbose_name='Тип')),
                ('action', models.TextField(verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.business', verbose_name='Бизнес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ['-created_at'],
            },
        ),
    ]
