# Generated by Django 4.2.30 on 2026-07-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_log_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Иконка')),
                ('db_table_name', models.CharField(max_length=63, unique=True, verbose_name='Имя таблицы в БД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tables', to='accounts.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Пользовательская таблица',
                'verbose_name_plural': 'Пользовательские таблицы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(max_length=100, verbose_name='Поле в исходной')),
                ('to_field', models.CharField(max_length=100, verbose_name='Поле в целевой')),
                ('rel_type', models.CharField(choices=[('one_to_many', 'Один-ко-многим'), ('many_to_many', 'Многие-ко-многим')], max_length=20, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='accounts.tableschema', verbose_name='Исходная таблица')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='accounts.tableschema', verbose_name='Целевая таблица')),
            ],
            options={
                'verbose_name': 'Связь таблиц',
                'verbose_name_plural': 'Связи таблиц',
            },
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Выбор'), ('multiselect', 'Мультивыбор'), ('boolean', 'Да/Нет'), ('email', 'Email'), ('phone', 'Телефон'), ('url', 'Ссылка'), ('file', 'Файл'), ('relation', 'Связь')], max_length=20, verbose_name='Тип')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('related_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.tableschema', verbose_name='Связанная таблица')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.tableschema', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Поле таблицы',
                'verbose_name_plural': 'Поля таблиц',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
