# Generated by Django 4.2.30 on 2026-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_custom_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableschema',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Товар'), ('supply', 'Поставка'), ('sale', 'Продажа'), ('custom', 'Пользовательская')], default='custom', max_length=20, verbose_name='Тип сущности'),
        ),
    ]
