# Generated by Django 4.2.30 on 2026-07-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('social_network', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'Max'), ('whatsapp', 'WhatsApp'), ('vk', 'VK')], default='telegram', max_length=10, verbose_name='Соцсеть')),
                ('social_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Юзернейм')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма покупок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-total_spent'],
            },
        ),
    ]
