# Generated by Django 4.2.30 on 2026-07-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='site_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес сайта'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_color_scheme',
            field=models.JSONField(blank=True, default=dict, verbose_name='Цветовая схема'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email сайта'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон сайта'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='business',
            name='site_work_hours',
            field=models.CharField(blank=True, default='Пн–Пт, 9:00–18:00', max_length=100, verbose_name='Часы работы'),
        ),
    ]
