# Generated by Django 4.2.30 on 2026-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Кастомные поля'),
        ),
        migrations.AddField(
            model_name='sale',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Кастомные поля'),
        ),
        migrations.AddField(
            model_name='supply',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Кастомные поля'),
        ),
    ]
