# Generated by Django 4.2.30 on 2026-07-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_business_site_settings'),
        ('inventory', '0002_add_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email клиента')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('items', models.JSONField(default=list, verbose_name='Товары')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
