# Generated by Django 4.2.30 on 2026-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В работе'), ('completed', 'Выполнен')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
