# Generated by Django 4.2.30 on 2026-07-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_business_site_settings'),
        ('inventory', '0004_order_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.business', verbose_name='Бизнес'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.business', verbose_name='Бизнес'),
        ),
        migrations.AddField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.business', verbose_name='Бизнес'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.business', verbose_name='Бизнес'),
        ),
        migrations.AddField(
            model_name='supply',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='accounts.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('pending', 'Заказ в работе'), ('cancelled', 'Отменена')], default='completed', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('business', 'name')},
        ),
    ]
